# Generated by Django 3.2 on 2021-04-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_surname', models.CharField(max_length=100)),
                ('patient_phonenumber', models.IntegerField(max_length=100)),
                ('patient_checkDate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservationtoken',
            name='reservation',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='ReservationToken',
        ),
    ]
